<?php
/**
 * @author Stardiggers Team
 * @author Evgeni Obukhovsky <eobuhovsky@gmail.com>
 * @copyright Copyright (c) 2017 Stardiggers (https://www.stardiggers.com)
 * @package Stardiggers_Googlesurvey
 */

/** @var Stardiggers_Googlesurvey_Block_Badge $this */
?>
<?php if ($this->getLanguage()): ?>
    <script>
        window.___gcfg = {
            lang: "<?php echo $this->escapeHtml($this->getLanguage()) ?>"
        };
    </script>
<?php endif; ?>
<script src="https://apis.google.com/js/platform.js" async defer></script>​
<g:ratingbadge merchant_id=<?php echo $this->escapeHtml($this->getMerchantId()) ?>></g:ratingbadge>​